In [1]:
import pandas as pd
import os

# Data Loading

In [2]:
os.chdir("../")
os.chdir("../ML_Finance_Project_files/data/raw")
df = pd.read_csv("raw_data.csv")

# Schema Validation

In [3]:
print(f"Shape: {df.shape}")
print(f"Unique Tickers: {df['Ticker'].nunique()}")

Shape: (61780, 7)
Unique Tickers: 25

In [4]:
df.head()

         Date       Open       High        Low      Close     Volume Ticker
0  2015-01-02  27.847500  27.860001  26.837500  27.332500  212818400   AAPL
1  2015-01-05  27.072500  27.162500  26.352501  26.562500  257142000   AAPL
2  2015-01-06  26.635000  26.857500  26.157499  26.565001  263188400   AAPL
3  2015-01-07  26.799999  27.049999  26.674999  26.937500  160423600   AAPL
4  2015-01-08  27.307501  28.037500  27.174999  27.972500  237458000   AAPL

In [5]:
print(df.dtypes)

Date       object
Open      float64
High      float64
Low       float64
Close     float64
Volume      int64
Ticker     object
dtype: object

# Missing Value Analysis

In [6]:
print(df.isnull().sum())

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
Ticker    0
dtype: int64

In [7]:
print(df['Ticker'].value_counts())

Ticker
AAPL     2515
MSFT     2515
NVDA     2515
GOOGL    2515
AMZN     2515
META     2515
TSLA     2515
JPM      2515
GS       2515
BAC      2515
WFC      2515
C        2515
MS       2515
SPY      2515
QQQ      2515
DIA      2515
VTI      2515
ARKK     2515
XLF      2515
XLK      2515
INTC     2515
AMD      2515
CRM      2515
ORCL     2515
UBER     1420
Name: count, dtype: int64

# Duplicates Check

In [8]:
print(df.duplicated().sum())

0

# Ticker Distribution

In [9]:
df['Date'] = pd.to_datetime(df['Date'])

In [10]:
df = df.sort_values(by=["Ticker", "Date"])

In [11]:
df.to_csv("validated_data.csv")

In [ ]:
enhanced_df = pd.read_csv("features/enhanced_features.csv")

In [17]:
enhanced_df.head(20)

,Unnamed: 0,Date,Open,High,Low,Close,Volume,Ticker,Daily_Return,Target,...,Volatility_5,Price_VS_SMA5,Price_VS_SMA20,Momentum_5,RSI_14,Return_Lag1,Return_Lag2,Return_Lag3,Close_Lag1,Close_Lag2
0,20,2015-02-02,29.512501,29.792500,29.020000,29.657499,250956400,AAPL,0.012547,1,...,0.036233,0.024191,0.067714,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,21,2015-02-03,29.625000,29.772499,29.402500,29.662500,207662800,AAPL,0.000169,1,...,0.027687,0.007815,0.061968,NaN,NaN,0.012547,NaN,NaN,29.657499,NaN
2,22,2015-02-04,29.625000,30.127501,29.577499,29.889999,280598800,AAPL,0.007670,1,...,0.016790,0.008264,0.063781,NaN,NaN,0.000169,0.012547,NaN,29.662500,29.657499
3,23,2015-02-05,30.004999,30.057501,29.812500,29.985001,168984800,AAPL,0.003178,0,...,0.010303,0.009698,0.061407,NaN,NaN,0.007670,0.000169,0.012547,29.889999,29.662500
4,24,2015-02-06,30.004999,30.062500,29.612499,29.732500,174826400,AAPL,-0.008421,1,...,0.007928,-0.001779,0.049200,NaN,NaN,0.003178,0.007670,0.000169,29.985001,29.889999
5,25,2015-02-09,29.637501,29.959999,29.607500,29.930000,155559200,AAPL,0.006643,1,...,0.006460,0.003016,0.052590,0.272501,NaN,-0.008421,0.003178,0.007670,29.732500,29.985001
6,26,2015-02-10,30.042500,30.537500,30.040001,30.504999,248034000,AAPL,0.019211,1,...,0.009913,0.016545,0.066823,0.842499,NaN,0.006643,-0.008421,0.003178,29.930000,29.732500
7,27,2015-02-11,30.692499,31.230000,30.625000,31.219999,294247200,AAPL,0.023439,1,...,0.012801,0.031231,0.084875,1.330000,NaN,0.019211,0.006643,-0.008421,30.504999,29.930000
8,28,2015-02-12,31.514999,31.870001,31.392500,31.615000,297898000,AAPL,0.012652,1,...,0.012456,0.033153,0.090708,1.629999,NaN,0.023439,0.019211,0.006643,31.219999,30.504999
9,29,2015-02-13,31.820000,31.820000,31.412500,31.770000,217088800,AAPL,0.004903,1,...,0.007953,0.024574,0.086562,2.037500,NaN,0.012652,0.023439,0.019211,31.615000,31.219999
10,30,2015-02-17,31.872499,32.220001,31.730000,31.957500,252609600,AAPL,0.005902,1,...,0.008114,0.017317,0.082865,2.027500,NaN,0.004903,0.012652,0.023439,31.770000,31.615000
11,31,2015-02-18,31.907499,32.195000,31.862499,32.180000,179566800,AAPL,0.006962,0,...,0.007692,0.013591,0.081245,1.675001,NaN,0.005902,0.004903,0.012652,31.957500,31.770000
12,32,2015-02-19,32.119999,32.257500,32.082500,32.112499,149449600,AAPL,-0.002098,1,...,0.005277,0.005810,0.070479,0.892500,NaN,0.006962,0.005902,0.004903,32.180000,31.957500
13,33,2015-02-20,32.154999,32.375000,32.012501,32.375000,195793600,AAPL,0.008174,1,...,0.004027,0.009227,0.071594,0.760000,NaN,-0.002098,0.006962,0.005902,32.112499,32.180000
14,34,2015-02-23,32.505001,33.250000,32.415001,33.250000,283896400,AAPL,0.027027,0,...,0.010751,0.027027,0.091515,1.480000,92.439426,0.008174,-0.002098,0.006962,32.375000,32.112499
15,35,2015-02-24,33.235001,33.400002,32.792500,33.042500,276912400,AAPL,-0.006241,0,...,0.012848,0.013822,0.076281,1.084999,88.105938,0.027027,0.008174,-0.002098,33.250000,32.375000
16,36,2015-02-25,32.889999,32.900002,32.037498,32.197498,298846800,AAPL,-0.025573,1,...,0.019328,-0.012210,0.040433,0.017498,72.835195,-0.006241,0.027027,0.008174,33.042500,33.250000
17,37,2015-02-26,32.197498,32.717499,31.652500,32.605000,365150000,AAPL,0.012656,0,...,0.019993,-0.002722,0.047210,0.492500,74.417486,-0.025573,-0.006241,0.027027,32.197498,33.042500
18,38,2015-02-27,32.500000,32.642502,32.060001,32.115002,248059200,AAPL,-0.015028,1,...,0.021208,-0.016145,0.027528,-0.259998,71.262833,0.012656,-0.025573,-0.006241,32.605000,32.197498
19,39,2015-03-02,32.312500,32.570000,32.075001,32.272499,192386800,AAPL,0.004904,1,...,0.015261,-0.005363,0.027664,-0.977501,71.056169,-0.015028,0.012656,-0.025573,32.115002,32.605000